---
- hosts: "managers"
  remote_user: ubuntu
  connection: ssh

  tasks:
  - name: install weave cni plugin 
    shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    run_once: true  #on first manager 